linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gofmt
    - golint
    - gosimple
    - ineffassign
    - misspell
    - staticcheck
    - structcheck
    - unconvert
    - unused
    - varcheck
    - vet

output:
  format: tab

run:
  deadline: 10m
