dist: xenial
language: go
os: linux

go:
  - "1.13.x"
  - "1.14.x"
  - tip

cache:
  directories:
    - .bin/

jobs:
  fast_finish: true
  allow_failures:
    - go: tip
  include:
    - name: "Lint"
      script: make tools lint
    - name: "Test"
      script: make test
